version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management console
      - "61613:61613" # STOMP plugin port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PLUGINS_DIR: /opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbit/plugins:/usr/lib/rabbitmq/plugins

volumes:
  rabbitmq_data: